theme: jekyll-theme-minimal
title: "Robb Surridge"
description: "A portfolio of selected recent writing and design projects."
cv_url: "/docs/robb_surridge_cv.pdf"
github_url: "https://github.com/bbor/"
linkedin_url: "https://www.linkedin.com/in/robb-surridge-6547533/"
